name: Ping Website every 13 minutes

# Run this workflow every 13 minutes
on:
  workflow_dispatch:
  schedule:
    - cron: "*/13 * * * *"

jobs:
  ping:
    runs-on: ubuntu-latest
    steps:
      - name: Ping website
        run: curl https://x-hub-2jff.onrender.com || echo "Failed to ping website"
